// this node.js script reads "words_alpha.txt",
// keeps only 5-letter words, and saves them into
// a new file called "words.js" to use for the game
// the word.js file is only created after running this script in the terminal

const fs = require('fs');      // fs = File System module (used to read/write files)
const path = require('path');  // path = helps build file paths safely for all OS

// Set up file locations
const inputFile = path.join(__dirname, 'words_alpha.txt'); // input text file (the big dictionary)
const outputFile = path.join(__dirname, 'words.js');       // output JS file to save filtered words

try {
  console.log("🔍 Reading words_alpha.txt..."); // Let user know the script started reading
  const text = fs.readFileSync(inputFile, 'utf8'); // Read the entire file as plain text (UTF-8)

  console.log("📖 Filtering 5-letter words..."); // Let user know it's filtering now
  const fiveLetterWords = text
    .split(/\r?\n/) // Split text into an array by line breaks 
    .filter(w => /^[a-z]{5}$/i.test(w)) // Keep only words with exactly 5 letters (no symbols/numbers)
    .map(w => w.toLowerCase()); // Convert all words to lowercase for consistency

  console.log(`✅ Found ${fiveLetterWords.length.toLocaleString()} five-letter words.`); // Log how many were found

  // Create the text that will be written to "words.js"
  const jsContent = 
`// Auto-generated list of all 5-letter English words
// Generated by filterWords.js
const wordList = ${JSON.stringify(fiveLetterWords, null, 2)};
`;

  // Save the filtered list into words.js
  fs.writeFileSync(outputFile, jsContent, 'utf8'); // Write the data to a new JS file

  console.log(`💾 Created ${outputFile} with ${fiveLetterWords.length.toLocaleString()} words.`); // Confirm success
} catch (err) {
  // If something goes wrong (like missing file), show the error
  console.error("❌ Error:", err.message);
}
